apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ops
  labels:
    app: cloud-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-ops
  template:
    metadata:
      labels:
        app: cloud-ops
    spec:
      containers:
      - name: cloud-ops
        image: <your-docker-image>
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
