name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build_and_test:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Bazel
      uses: actions/setup-bazel@v1
      with:
        version: '5.4.0'

    - name: Build the binaries with Bazel
      run: |
        bazel build //...

    - name: Run Tests
      run: |
        bazel test //...

  upload_artifacts:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '.0.0') || contains(github.ref, '.0') || contains(github.ref, '.'))

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bazel-bin/cmd/cloud-ops/cloud-ops